### ISSUE TITLE
我下载了 Oil-Polution-Dataset，运行代码时报错了。

### ISSUE THREAD

**Issue by aitangbodan** [HengWeiBin/Oil-Polution-Dataset-with-PIDNet#1]
=> creating log/oilpollution/pidnet_small/pidnet_small_oil_raw_2023-05-09-14-46
<class 'datasets.elanroad.ElanRoad'>
Epoch: [1/175] Iter:[5/169], lr: ['0.009999'], Loss: 145.18, Acc:0.00, Semantic loss:
Traceback (most recent call last):
  File "tools/train.py", line 221, in <module>
    main()
  File "tools/train.py", line 184, in main
    train(config, epoch, config.TRAIN.END_EPOCH,
  File "/home/Oil-Polution-Dataset-with-PIDNet/tools/../utils/function.py", line 42, in train
    losses, _, acc, loss_list = model(images, labels, bd_gts)
  File "/home/.conda/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/.conda/envs/pytorch/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/.conda/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Oil-Polution-Dataset-with-PIDNet/tools/../utils/utils.py", line 54, in forward
    loss_sb = self.sem_loss(outputs[-2], bd_label)
  File "/home/.conda/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Oil-Polution-Dataset-with-PIDNet/tools/../utils/criterion.py", line 105, in forward
    return sb_weights * self._ohem_forward(score[0], target)
  File "/home/Oil-Polution-Dataset-with-PIDNet/tools/../utils/criterion.py", line 81, in _ohem_forward
    min_value = pred[min(self.min_kept, pred.numel() - 1)]
IndexError: index -1 is out of bounds for dimension 0 with size 0

**Comment by maybei** [comment]
-1 is out of bound .  so you can change this way.
        if min(self.min_kept, pred.numel() - 1) >0 :
            min_value = pred[min(self.min_kept, pred.numel() - 1)]
        else:
            min_value = 1
hope you helpful~

**Comment by snachi2s** [comment]
Try changing the `BASE_SIZE` parameter in config file. 
It solves the error mostly!!
